do
Mensaje=msgbox("Hola" ,16, "Mensaje")
Mensaje=msgbox("¿Qué haces?" ,16, "Mensaje")
Mensaje=msgbox("Quieres salir?" ,16, "Mensaje")
Mensaje=msgbox("Estas segur@?" ,16, "Mensaje")
Mensaje=msgbox("Pero no puedes" ,16, "Mensaje")
Message=msgbox("Hello" ,16, "Message")
Message=msgbox("What are you doing?" ,16, "Message")
Message=msgbox("Do you want to exit?" ,16, "Message")
Message=msgbox("Are you sure?" ,16, "Message")
Message=msgbox("But you can't" ,16, "Message")
Message=msgbox("Salve" ,16, "Messagium")
Message=msgbox("Quid facis?" ,16, "Messagium")
Message=msgbox("Visne exire?" ,16, "Messagium")
Message=msgbox("Certus es?" ,16, "Messagium")
Message=msgbox("Sed non potes" ,16, "Messagium")
Message=msgbox("Привет" ,16, "Сообщение")
Message=msgbox("Что ты делаешь?" ,16, "Сообщение")
Message=msgbox("Хочешь выйти?" ,16, "Сообщение")
Message=msgbox("Ты уверен(а)?" ,16, "Сообщение")
Message=msgbox("Но ты не можешь" ,16, "Сообщение")
Message=msgbox("你好" ,16, "消息")
Message=msgbox("你在做什么？" ,16, "消息")
Message=msgbox("你想退出吗？" ,16, "消息")
Message=msgbox("你确定吗？" ,16, "消息")
Message=msgbox("但你不能" ,16, "消息")
loop 